# Generated by Django 3.2.2 on 2021-05-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmedCases', models.IntegerField(default=0, verbose_name='confirmedCases')),
                ('deaths', models.IntegerField(default=0)),
                ('recovered', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
    ]
